export const ActionTypes = {
  SET_EMPLOYEES: "SET_EMPLOYEES",
  SELECTED_EMPLOYEE: "SELECTED_EMPLOYEE",
  REMOVE_EMPLOYEE_SUCC: "REMOVE_EMPLOYEE_SUCC",
  REMOVE_EMPLOYEE_ERR: "REMOVE_EMPLOYEE_ERR",
  UPDATE_EMPLOYEE: "UPDATE_EMPLOYEE",
};
